name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # FETCH FROM REPOSITORY
      - name: Checkout code
        uses: actions/checkout@v4

      # SETUP .NET (for unit tests)
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # RESTORE DEPENDENCIES
      - name: Restore
        run: dotnet restore

      # BUILD SOLUTION
      - name: Build
        run: dotnet build --no-restore

      # RUN UNIT TESTS
      - name: Run unit tests
        run: dotnet test --no-build

      # DockerHub LOGIN
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and fetch image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/tripmate:latest
            ${{ secrets.DOCKER_USERNAME }}/tripmate:${{ github.sha }}

      # DEPLOY TO AZURE WEB APP
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: tripmate
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/tripmate:latest
